### ISSUE TITLE
fix major bugs

### ISSUE THREAD

**Issue by l3wl3w00** [BME-MIT-IET/iet-hf-2023-vakanet#7]
With SonarCloud added it shows there are 7 major bugs in the code, all of which takes from 3 to 15 minutes to solve, so I created one issue for all of them

**Comment by Andromeda08** [comment]
I'm eagerly working on fixing the 7 major bugs found by SonarCloud in the code @l3wl3w00!

You know where to find me if you need anything!

Best regards,
Github user Andromeda08

**Comment by Andromeda08** [comment]
The major bugs found by SonarCloud have been fixed.
