### ISSUE TITLE
fix blocker bugs

### ISSUE THREAD

**Issue by l3wl3w00** [BME-MIT-IET/iet-hf-2023-vakanet#8]
With SonarCloud added it shows there are 2 blocker bugs in the code, and both takes about 5 minutes to fix, so I opened one issue for both.

**Comment by l3wl3w00** [comment]
started working on this one

**Comment by Andromeda08** [comment]
Since Java 19 the `ExecutorService` class implements the `AutoClosable` interface, and now can be surrounded in a try-with-resources statement.
This bumps the minimum JDK version of the project to 19, however this shouldn't be an issue as the maven has already been building with it.

**Comment by Andromeda08** [comment]
Fixed by commit cb1cb9e.
